const photo = (bucket, key) =>
  `https://${bucket}.s3.us-east-2.amazonaws.com/${key}`;
export const collections = [
  {
    slug: "9-1-2023",
    title: "Chicago at dusk.",
    name: "Chicago River at Sunset",
    year: "September 2023",
    category: "Places",
    description: "Photographs along the Chicago River in September 2023.",
    cover: photo("9-1-2023", "Sep1O-215.jpeg"),
    bucket: "9-1-2023",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_9_1_2023",
    pattern: "^Sep1(O?)-(\\d+)\\.(jpe?g)$",
  },
  {
    slug: "masters-graduation",
    title: "Master’s graduation.",
    name: "Master’s Graduation",
    year: "May 2025",
    category: "Milestones",
    description:
      "Graduation photographs from Mississippi College, where I earned my M.S. in Biological Sciences in May 2025.",
    cover: photo("masters-graduation", "GRADO-6793.jpeg"),
    bucket: "masters-graduation",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_MASTERS_GRADUATION",
    pattern: "^GRAD(O?)-(\\d+)\\.(jpe?g)$",
  },
  {
    slug: "daddy-daughter-photoshoot",
    title: "My daughter and me.",
    name: "Daddy-Daughter Portraits",
    year: "Family",
    category: "People",
    description: "Portraits of my daughter and me.",
    cover: photo("daddy-daughter-photoshoot", "E13-E.jpg"),
    bucket: "daddy-daughter-photoshoot",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_DADDY_DAUGHTER_PHOTOSHOOT",
    credit: "Photography by JSHcreates",
    creditHref: "https://jshcreates.com",
  },
  {
    slug: "gatlinburg-25",
    title: "Gatlinburg, 2025.",
    name: "Gatlinburg",
    year: "2025",
    category: "Places",
    description: "Photographs from my 2025 trip to Gatlinburg.",
    cover: photo("gatlinburg-25", "GATO-6612.jpeg"),
    bucket: "gatlinburg-25",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_GATLINBURG_25",
    pattern: "^GAT(O?)-(\\d+)\\.(jpe?g)$",
  },
  {
    slug: "apple-day-23",
    title: "Apple Day, 2023.",
    name: "Apple Day",
    year: "2023",
    category: "Moments",
    description: "Photographs from Apple Day in 2023.",
    cover: photo("apple-day-23", "ADO-83.jpeg"),
    bucket: "apple-day-23",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_APPLE_DAY_23",
    pattern: "^AD(O?)-(\\d+)\\.(jpe?g)$",
  },
  {
    slug: "chicago-marathon-23",
    title: "Chicago Marathon Week.",
    name: "Chicago Marathon Week",
    year: "2023",
    category: "Places",
    description: "Photographs taken during Chicago Marathon Week in 2023.",
    cover: photo("chicago-marathon-23", "CMO-40.png"),
    bucket: "chicago-marathon-23",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_CHICAGO_MARATHON_23",
    pattern: "^CM(O)-(\\d+)\\.(png)$",
  },
  {
    slug: "texas-state-fair",
    title: "A day at the fair.",
    name: "Texas State Fair",
    year: "2023",
    category: "Moments",
    description: "A photographic collection from the Texas State Fair.",
    cover: photo("texas-state-fair", "Texas-State-Fair-82.jpg"),
    bucket: "texas-state-fair",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_TEXAS_STATE_FAIR",
  },
  {
    slug: "bachelors-graduation",
    title: "Bachelor’s graduation.",
    name: "Bachelor’s Graduation",
    year: "Jackson State University",
    category: "Milestones",
    description:
      "Celebrating a Bachelor of Science in Biology at Jackson State University.",
    cover: photo("bachelors-graduation", "GRAD-JSU-O-748.jpeg"),
    bucket: "bachelors-graduation",
    env: "NEXT_PUBLIC_S3_BUCKET_ALBUM_BACHELORS_GRADUATION",
    pattern: "^GRAD-JSU-(O-)?(\\d+)\\.(jpe?g)$",
  },
];
export const portrait = photo("masters-graduation", "GRADO-6789.jpeg");
